#!/bin/bash
flags="-Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-unused-parameter -Iinclude -O3 -ffast-math -flto -std=c++17"
echo "Compiling server" && (g++ -o ./bin/server ./tests/server/server.cpp $flags) && \
echo "Compiling client" && (g++ -o ./bin/client ./tests/client/client.cpp $flags)
#./bin/server &
#./bin/client
